title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Caleb Jones Shibu 
  <br><br>
  Bachelors of Engineering Computer Science
  <br><br>
  <a href="https://www.linkedin.com/in/caleb-jones-shibu-520836146/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-modernist
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
